CREATE TABLE Orders (
    OrderId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerName VARCHAR2(100),
    OrderDate DATE
);

CREATE TABLE OrderItems (
    OrderItemId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId NUMBER REFERENCES Orders(OrderId),
    ProductName VARCHAR2(100),
    Quantity NUMBER,
    Price NUMBER
);


